CREATE TABLE IF NOT EXISTS PRODUCT
(
    ID   BIGINT AUTO_INCREMENT NOT NULL,
    NAME VARCHAR(255),
    CONSTRAINT PK_PRODUCT PRIMARY KEY (ID)
    );

CREATE TABLE IF NOT EXISTS BRAND
(
    ID   BIGINT AUTO_INCREMENT NOT NULL,
    NAME VARCHAR(255),
    CONSTRAINT PK_BRAND PRIMARY KEY (ID)
    );

CREATE TABLE IF NOT EXISTS PRICE_LIST
(
    ID   BIGINT AUTO_INCREMENT NOT NULL,
    NAME VARCHAR(255),
    CONSTRAINT PK_PRICE_LIST PRIMARY KEY (ID)
    );

CREATE TABLE IF NOT EXISTS PRICE
(
    ID            BIGINT AUTO_INCREMENT               NOT NULL,
    START_DATE    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    END_DATE      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRICE         DOUBLE PRECISION                    NOT NULL,
    CURR          VARCHAR(3)                          NOT NULL,
    PRIORITY      INTEGER                             NOT NULL,
    BRAND_ID      BIGINT                              NOT NULL,
    PRODUCT_ID    BIGINT                              NOT NULL,
    PRICE_LIST_ID BIGINT                              NOT NULL,
    CONSTRAINT PK_PRICE PRIMARY KEY (ID),
    CONSTRAINT FK_PRICE_ON_BRAND FOREIGN KEY (BRAND_ID) REFERENCES BRAND (ID),
    CONSTRAINT FK_PRICE_ON_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID),
    CONSTRAINT FK_PRICE_ON_PRICE_LIST FOREIGN KEY (PRICE_LIST_ID) REFERENCES PRICE_LIST (ID)
    );

CREATE INDEX price_start_date_idx ON PRICE(START_DATE);
CREATE INDEX price_end_date_idx ON PRICE(END_DATE);
